version: '3.1'
services:
  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: exampleRoot
      MYSQL_DATABASE: InfoClients
      MYSQL_USER: infoClientUserDb
      MYSQL_PASSWORD: infoClientUserPwd*!
  adminer:
    container_name: admin_db
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 8080:8080
