-- MySQL Script generated by MySQL Workbench
-- lun 30 sep 2019 01:04:33 -05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema InfoClients
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `InfoClients` ;

-- -----------------------------------------------------
-- Schema InfoClients
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `InfoClients` DEFAULT CHARACTER SET utf8 ;
USE `InfoClients` ;

-- -----------------------------------------------------
-- Table `InfoClients`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InfoClients`.`country` ;

CREATE TABLE IF NOT EXISTS `InfoClients`.`country` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InfoClients`.`state`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InfoClients`.`state` ;

CREATE TABLE IF NOT EXISTS `InfoClients`.`state` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `country_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_state_country1_idx` (`country_id` ASC),
  CONSTRAINT `fk_state_country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `InfoClients`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InfoClients`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InfoClients`.`city` ;

CREATE TABLE IF NOT EXISTS `InfoClients`.`city` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `state_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_city_state1_idx` (`state_id` ASC),
  CONSTRAINT `fk_city_state1`
    FOREIGN KEY (`state_id`)
    REFERENCES `InfoClients`.`state` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InfoClients`.`sales_representative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InfoClients`.`sales_representative` ;

CREATE TABLE IF NOT EXISTS `InfoClients`.`sales_representative` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InfoClients`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InfoClients`.`customers` ;

CREATE TABLE IF NOT EXISTS `InfoClients`.`customers` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `credit_limit` FLOAT NULL,
  `available_credit` FLOAT NULL,
  `visits_percentage` FLOAT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customers_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_customers_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `InfoClients`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `InfoClients`.`visits`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `InfoClients`.`visits` ;

CREATE TABLE IF NOT EXISTS `InfoClients`.`visits` (
  `id` INT NOT NULL,
  `date` VARCHAR(45) NULL,
  `net` FLOAT NULL,
  `visit_total` FLOAT NULL,
  `description` VARCHAR(45) NULL,
  `sales_representative_id` INT NOT NULL,
  `customers_id` INT NOT NULL,
  PRIMARY KEY (`id`, `sales_representative_id`, `customers_id`),
  INDEX `fk_visits_sales_representative1_idx` (`sales_representative_id` ASC),
  INDEX `fk_visits_customers1_idx` (`customers_id` ASC),
  CONSTRAINT `fk_visits_sales_representative1`
    FOREIGN KEY (`sales_representative_id`)
    REFERENCES `InfoClients`.`sales_representative` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_visits_customers1`
    FOREIGN KEY (`customers_id`)
    REFERENCES `InfoClients`.`customers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
